import { useState } from "react";
import { Folder, FileText, Play, Check, RefreshCw } from "lucide-react";

export function CodingIDE() {
  const [selectedFile, setSelectedFile] = useState("app.py");

  const files = [
    "app.py",
    "requirements.txt",
    "Dockerfile",
    "config.yaml",
  ];

  return (
    <div className="flex-1 flex bg-bg-0 h-screen overflow-hidden">
      {/* File Tree */}
      <div className="w-56 glass-soft border-r border-white/5 p-4 space-y-3">
        <span className="text-xs font-semibold text-text-2 uppercase tracking-wider block">Explorer</span>
        <div className="space-y-1">
          {files.map((file) => (
            <button
              key={file}
              onClick={() => setSelectedFile(file)}
              className={`w-full flex items-center space-x-2 px-3 py-1.5 rounded-lg text-xs font-mono transition-colors ${
                selectedFile === file ? "bg-white/10 text-primary-400" : "text-text-2 hover:bg-white/5 hover:text-text-0"
              }`}
            >
              <FileText size={14} />
              <span>{file}</span>
            </button>
          ))}
        </div>
      </div>

      {/* Editor & Diff Preview */}
      <div className="flex-1 flex flex-col border-r border-white/5">
        <div className="h-10 border-b border-white/5 px-4 flex items-center justify-between text-xs text-text-2 font-mono">
          <span>{selectedFile}</span>
          <span className="text-emerald-400 font-semibold">Diff Mode: +12 / -2</span>
        </div>
        <div className="flex-1 p-4 font-mono text-xs text-text-0 bg-bg-1 overflow-auto space-y-1">
          <div className="text-text-2"># Auto-generated by MAGoCo Agent</div>
          <div className="text-purple-400">import <span className="text-text-0">os</span></div>
          <div className="text-purple-400">import <span className="text-text-0">asyncio</span></div>
          <div className="py-2"></div>
          <div className="text-emerald-400 bg-emerald-500/10 px-2 py-0.5 rounded">+ def run_agent_task(prompt: str):</div>
          <div className="text-emerald-400 bg-emerald-500/10 px-2 py-0.5 rounded">+     print(f"Executing: {prompt}")</div>
          <div className="text-red-400 bg-red-500/10 px-2 py-0.5 rounded line-through">- print("Legacy execution")</div>
        </div>
      </div>
    </div>
  );
}
