"""Curated BEST-OF skill bank — imported from world-class open-source repos.

Strategy (NOT bulk copy): ~25 highest-signal skills, each with source_url for
provenance + license respect. The importer (importer.py) can fetch any SKILL.md
by URL, so this catalog grows without code changes.

Sources: anthropics/skills (official), mattpocock/skills (engineering),
obra/superpowers (+superpowers-skills), trailofbits/skills (security),
ComposioHQ/awesome-claude-skills, xcodethink collection.
"""

from __future__ import annotations

from typing Any, Dict, List


# Each entry: id, display_name, description, category (our SkillCategory value),
# type, tags (used by auto-detection), source_url, author
SEED_CATALOG: List[Dict[str, Any]] = [
    # ---- Official Anthropic (document + web) ----
    {"id": "docx", "display_name": "DOCX Documents",
     "description": "Create and edit Microsoft Word documents with formatting, comments, tracked changes.",
     "category": "productivity", "type": "workflow",
     "tags": ["document", "word", "report", "writing"],
     "source_url": "https://github.com/anthropics/skills/tree/main/skills/docx", "author": "anthropic"},
    {"id": "pdf", "display_name": "PDF Toolkit",
     "description": "Extract content from PDFs, split/merge documents, create new ones.",
     "category": "productivity", "type": "workflow",
     "tags": ["document", "pdf", "research", "extract"],
     "source_url": "https://github.com/anthropics/skills/tree/main/skills/pdf", "author": "anthropic"},
    {"id": "pptx", "display_name": "PPTX Presentations",
     "description": "Generate and edit PowerPoint presentations.",
     "category": "productivity", "type": "workflow",
     "tags": ["document", "slides", "presentation"],
     "source_url": "https://github.com/anthropics/skills/tree/main/skills/pptx", "author": "anthropic"},
    {"id": "xlsx", "display_name": "XLSX Spreadsheets",
     "description": "Manipulate Excel files: formulas, tables, charts.",
     "category": "data_processing", "type": "workflow",
     "tags": ["document", "excel", "data", "finance"],
     "source_url": "https://github.com/anthropics/skills/tree/main/skills/xlsx", "author": "anthropic"},
    {"id": "webapp-testing", "display_name": "Webapp Testing",
     "description": "UI test automation using Playwright.",
     "category": "development", "type": "workflow",
     "tags": ["testing", "playwright", "browser", "e2e", "frontend"],
     "source_url": "https://github.com/anthropics/skills/tree/main/skills/webapp-testing", "author": "anthropic"},
    {"id": "skill-creator", "display_name": "Skill Creator",
     "description": "Meta-skill: create new well-formed skills with frontmatter and tests.",
     "category": "productivity", "type": "workflow",
     "tags": ["meta", "skill", "authoring"],
     "source_url": "https://github.com/anthropics/skills/tree/main/skills/skill-creator", "author": "anthropic"},
    {"id": "frontend-design", "display_name": "Frontend Design",
     "description": "Build web components, pages, artifacts with modern frontend design principles.",
     "category": "development", "type": "workflow",
     "tags": ["frontend", "design", "react", "ui", "css"],
     "source_url": "https://github.com/anthropics/skills/tree/main/skills/frontend-design", "author": "anthropic"},
    # ---- mattpocock engineering suite ----
    {"id": "tdd", "display_name": "TDD Workflow",
     "description": "Red-green-refactor loop with vertical slices for safer implementation.",
     "category": "development", "type": "workflow",
     "tags": ["testing", "tdd", "quality", "engineering"],
     "source_url": "https://github.com/mattpocock/skills/tree/main/skills/engineering/tdd", "author": "mattpocock"},
    {"id": "diagnosing-bugs", "display_name": "Diagnosing Bugs",
     "description": "Disciplined loop: reproduce, minimize, hypothesize, instrument, fix, regression-test.",
     "category": "development", "type": "workflow",
     "tags": ["debugging", "bug", "engineering", "testing"],
     "source_url": "https://github.com/mattpocock/skills/tree/main/skills/engineering/diagnosing-bugs", "author": "mattpocock"},
    {"id": "code-review", "display_name": "Code Review (2-axis)",
     "description": "Parallel review vs coding standards AND originating spec/PRD.",
     "category": "development", "type": "workflow",
     "tags": ["review", "quality", "engineering"],
     "source_url": "https://github.com/mattpocock/skills/tree/main/skills/engineering/code-review", "author": "mattpocock"},
    {"id": "implement", "display_name": "Implement from Spec",
     "description": "Implement work from a spec/tickets, driving TDD internally per issue.",
     "category": "development", "type": "workflow",
     "tags": ["implement", "spec", "engineering", "coding"],
     "source_url": "https://github.com/mattpocock/skills/tree/main/skills/engineering/implement", "author": "mattpocock"},
    {"id": "grill-me", "display_name": "Grill Me",
     "description": "Pressure-test plans and assumptions with relentless questions before execution.",
     "category": "productivity", "type": "workflow",
     "tags": ["planning", "review", "questions", "spec"],
     "source_url": "https://github.com/mattpocock/skills/tree/main/skills/productivity/grill-me", "author": "mattpocock"},
    {"id": "handoff", "display_name": "Handoff Notes",
     "description": "Compact transfer notes so another agent/session continues seamlessly.",
     "category": "productivity", "type": "workflow",
     "tags": ["handoff", "context", "collaboration", "sessions"],
     "source_url": "https://github.com/mattpocock/skills/tree/main/skills/productivity/handoff", "author": "mattpocock"},
    {"id": "to-spec", "display_name": "Conversation to Spec",
     "description": "Turn the current conversation into a published spec — synthesis, no interview.",
     "category": "productivity", "type": "workflow",
     "tags": ["spec", "planning", "synthesis"],
     "source_url": "https://github.com/mattpocock/skills/tree/main/skills/engineering/to-spec", "author": "mattpocock"},
    {"id": "to-tickets", "display_name": "Plan to Tickets",
     "description": "Break a plan/spec into tracer-bullet tickets with declared blocking edges.",
     "category": "productivity", "type": "workflow",
     "tags": ["tickets", "planning", "decomposition", "dependencies"],
     "source_url": "https://github.com/mattpocock/skills/tree/main/skills/engineering/to-tickets", "author": "mattpocock"},
    # ---- obra/superpowers ----
    {"id": "executing-plans", "display_name": "Executing Plans",
     "description": "Execute structured plans with checkpoints and verification steps.",
     "category": "automation", "type": "workflow",
     "tags": ["planning", "execution", "checkpoints", "verification"],
     "source_url": "https://github.com/obra/superpowers/tree/main/skills/executing-plans", "author": "obra"},
    {"id": "systematic-debugging", "display_name": "Systematic Debugging",
     "description": "Structured debugging with hypothesis testing and validation.",
     "category": "development", "type": "workflow",
     "tags": ["debugging", "testing", "hypothesis"],
     "source_url": "https://github.com/obra/superpowers/tree/main/skills/systematic-debugging", "author": "obra"},
    {"id": "verification-before-completion", "display_name": "Verify Before Completion",
     "description": "Run verification checks before closing tasks. Never confirm without proof.",
     "category": "development", "type": "workflow",
     "tags": ["verification", "quality", "anti-hallucination", "testing"],
     "source_url": "https://github.com/obra/superpowers/tree/main/skills/verification-before-completion", "author": "obra"},
    {"id": "dispatching-parallel-agents", "display_name": "Parallel Agents",
     "description": "Coordinate multiple subagents on shared tasks safely.",
     "category": "automation", "type": "workflow",
     "tags": ["multi-agent", "parallel", "coordination"],
     "source_url": "https://github.com/obra/superpowers/tree/main/skills/dispatching-parallel-agents", "author": "obra"},
    {"id": "brainstorming", "display_name": "Brainstorming",
     "description": "Facilitate creative idea generation sessions.",
     "category": "productivity", "type": "workflow",
     "tags": ["ideation", "planning", "creative"],
     "source_url": "https://github.com/obra/superpowers/tree/main/skills/brainstorming", "author": "obra"},
    {"id": "root-cause-tracing", "display_name": "Root Cause Tracing",
     "description": "Trace and diagnose the source of data or logic errors.",
     "category": "development", "type": "workflow",
     "tags": ["debugging", "data", "analysis"],
     "source_url": "https://github.com/obra/superpowers-skills/tree/main/skills/debugging/root-cause-tracing", "author": "obra"},
    # ---- Security ----
    {"id": "trailofbits-audit", "display_name": "Security Audit (Trail of Bits)",
     "description": "Static analysis with CodeQL/Semgrep, variant analysis, auditing, fix verification.",
     "category": "security", "type": "workflow",
     "tags": ["security", "audit", "codeql", "semgrep", "vulnerability"],
     "source_url": "https://github.com/trailofbits/skills", "author": "trailofbits"},
    {"id": "security-hardening", "display_name": "Security Hardening",
     "description": "Defensive workflow: secure design, OWASP, MCP security, prompt injection, hardening.",
     "category": "security", "type": "workflow",
     "tags": ["security", "owasp", "hardening", "review"],
     "source_url": "https://github.com/imnotStealthy/security-hardening", "author": "community"},
    # ---- Practicalofficial ----
    {"id": "stripe-best-practices", "display_name": "Stripe Best Practices",
     "description": "Official Stripe guidance: payments, subscriptions, webhooks done correctly.",
     "category": "api_integration", "type": "workflow",
     "tags": ["stripe", "payments", "saas", "billing", "webhooks"],
     "source_url": "https://github.com/stripe/ai/tree/main/skills/stripe-best-practices", "author": "stripe"},
    {"id": "playwright-skill", "display_name": "Playwright Automation",
     "description": "General browser automation with Playwright for testing and interaction.",
     "category": "development", "type": "workflow",
     "tags": ["browser", "playwright", "testing", "automation", "e2e"],
     "source_url": "https://github.com/lackeyjb/playwright-skill", "author": "community"},
]


def catalog_ids() -> list:
    return [s["id"] for s in SEED_CATALOG]
